"""
app/modules/dollar_exchange/service.py
========================================
CRUD for DollarExchange records.

SCHEMA FACTS (schema.prisma — ground truth):
  Field name   : paymentStatus            ← camelCase, matches schema exactly
  Enum type    : PaymentStatus            ← defined in schema.prisma
  Enum values  : RECEIVED | DUE           ← use these exact strings everywhere

PRISMA-CLIENT-PY RULES:
  create/update data dict  → "paymentStatus": "RECEIVED"  (exact schema field + enum value)
  where/filter dict        → "paymentStatus": "RECEIVED"  (same — both accept camelCase)
  Python attribute access  → r.paymentStatus              (auto-camelCase from schema)

NOTE ON .aggregate():
  prisma-client-py does NOT expose a model-level .aggregate() method.
  All aggregation is done via db.query_raw() with raw PostgreSQL SQL.
  Column names in raw SQL must match the actual DB column names (camelCase,
  quoted) as generated by Prisma from schema.prisma.
    schema field  totalBdt      →  DB column  "totalBdt"
    schema field  paymentStatus →  DB column  "paymentStatus"
    @@map("dollar_exchanges")   →  table name  dollar_exchanges
"""
from decimal import Decimal

from fastapi import HTTPException
from prisma import Prisma

from .schema import DollarExchangeCreate, DollarExchangeUpdate


async def create_exchange(db: Prisma, data: DollarExchangeCreate):
    """
    Create a new Dollar Exchange record.
    totalBdt is always computed from (credit or debit) × rate server-side.
    paymentStatus is stored using the Prisma enum string value: "RECEIVED" or "DUE".
    """
    return await db.dollarexchange.create(
        data={
            "date":          data.date,
            "details":       data.details,
            "accountFrom":   data.accountFrom,
            "accountTo":     data.accountTo,
            "debit":         data.debit,
            "credit":        data.credit,
            "rate":          data.rate,
            "totalBdt":       data.total_bdt,              # server-computed
            "paymentStatus":  data.payment_status.value,   # "RECEIVED" or "DUE"
        }
    )


async def list_exchanges(
    db: Prisma,
    date_filter: dict,
    payment_status: str | None = None,
):
    where: dict = {}
    if date_filter:
        where["date"] = date_filter
    if payment_status:
        # Normalise: accept "RCV" as legacy alias for "RECEIVED"
        status = "RECEIVED" if payment_status.upper() in ("RECEIVED", "RCV") else payment_status.upper()
        where["paymentStatus"] = status
    return await db.dollarexchange.find_many(where=where, order={"date": "desc"})


async def get_exchange(db: Prisma, exchange_id: str):
    record = await db.dollarexchange.find_unique(where={"id": exchange_id})
    if not record:
        raise HTTPException(status_code=404, detail="Exchange record not found")
    return record


async def update_exchange(db: Prisma, exchange_id: str, data: DollarExchangeUpdate):
    """
    Partial update.  If `rate` is changed, totalBdt is automatically
    recomputed using the existing debit/credit values on the record.
    """
    existing = await get_exchange(db, exchange_id)

    update_data: dict = {}

    if data.payment_status is not None:
        update_data["paymentStatus"] = data.payment_status.value  # "RECEIVED" or "DUE"

    if data.details is not None:
        update_data["details"] = data.details

    if data.accountFrom is not None:
        update_data["accountFrom"] = data.accountFrom

    if data.accountTo is not None:
        update_data["accountTo"] = data.accountTo

    if data.rate is not None:
        new_rate = data.rate
        # Recompute totalBdt with new rate using existing amounts
        exchange_amount = (
            existing.credit if (existing.credit and existing.credit > 0)
            else existing.debit or Decimal("0")
        )
        update_data["rate"]     = new_rate
        update_data["totalBdt"] = exchange_amount * new_rate

    if not update_data:
        return existing  # nothing to update — return unchanged

    return await db.dollarexchange.update(where={"id": exchange_id}, data=update_data)


async def delete_exchange(db: Prisma, exchange_id: str) -> None:
    await get_exchange(db, exchange_id)
    await db.dollarexchange.delete(where={"id": exchange_id})


async def get_total_bdt(db: Prisma) -> dict:
    """
    Return total BDT split by payment status.

    Uses query_raw() because prisma-client-py does NOT implement .aggregate()
    as a model-level action.  A single SQL pass computes all three figures
    (total / received / due) efficiently without fetching all rows.

    Table  : dollar_exchanges  (@@map in schema.prisma)
    Columns: "totalBdt", "paymentStatus"  (camelCase — Prisma does NOT
             auto-snake_case column names; they match the schema field name)
    """
    rows = await db.query_raw(
        """
        SELECT
            COALESCE(SUM("totalBdt"), 0)                                                  AS total,
            COALESCE(SUM(CASE WHEN "paymentStatus" = 'RECEIVED' THEN "totalBdt" END), 0) AS received,
            COALESCE(SUM(CASE WHEN "paymentStatus" = 'DUE'      THEN "totalBdt" END), 0) AS due
        FROM dollar_exchanges
        """
    )
    r = rows[0] if rows else {}
    return {
        "total":    float(r.get("total",    0) or 0),
        "received": float(r.get("received", 0) or 0),
        "due":      float(r.get("due",      0) or 0),
    }